### ISSUE TITLE
Module can't be installed from Foundry

### ISSUE THREAD

**Issue by Beardface123** [NickClearyTech/FoundryShopGenerator#3]
Receiving an error when attempting to install this module via Foundry's interface
```
Error: Unable to load valid module manifest data from "https://github.com/NickClearyTech/FoundryShopGenerator/blob/main/shop-generator/module.json"
The requested manifest at "https://github.com/NickClearyTech/FoundryShopGenerator/blob/main/shop-generator/module.json" did not provide module manifest data.
    at Module.installPackage (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/packages/views.mjs:1:1634)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SetupView.handlePost (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/server/views/setup.mjs:1:1980)
error @ setup.js:292
```

Using Foundry version 10 version 291

**Comment by nicleary** [comment]
Hi there! This should be fixed in versions 1.0.2 and above! Thanks for the report!
